version: 2
builder:
  configs:
  - platform: ios
    scheme: ReerKit
  - platform: macos
    scheme: ReerKit
  - platform: tvos
    scheme: ReerKit
  - platform: watchos
    scheme: ReerKit
  - platform: visionos
    scheme: ReerKit
  - platform: linux
    scheme: ReerKit
  - documentation_targets: ['ReerKit']
